# Rename this file to secrets.toml for local dev.
# In Streamlit Cloud, paste this content in App → Settings → Secrets.
[firebase]

[firebase.config]
apiKey = "AIzaSyBVT_9AjbZUONYLdtKVHjefS33ocV8Ee4E"
authDomain = "personalized-drink-recommender.firebaseapp.com"
projectId = "personalized-drink-recommender"
storageBucket = "personalized-drink-recommender.appspot.com"
messagingSenderId = "411582437245"
appId = "1:411582437245:web:be08a4cc3aa91d2f74de14"
measurementId = "G-NTF3JDYG4Z"

[firebase.service_account]
type = "service_account"
project_id = "personalized-drink-recommender"
private_key_id = "e13db3ba92143f6ce7a12dc467dd7f09ccd05104"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0B...\n-----END PRIVATE KEY-----\n"""
client_email = "firebase-adminsdk-fbsvc@personalized-drink-recommender.iam.gserviceaccount.com"
client_id = "102141272003078143238"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40personalized-drink-recommender.iam.gserviceaccount.com"

