[firebase]
apiKey = "AIzaSyBVT_9AjbZUONYLdtKVHjefS33ocV8Ee4E"
authDomain = "personalized-drink-recommender.firebaseapp.com"
projectId = "personalized-drink-recommender"
storageBucket = "personalized-drink-recommender.appspot.com"
messagingSenderId = "411582437245"
appId = "1:411582437245:web:be08a4cc3aa91d2f74de14"
measurementId = "G-NTF3JDYG4Z"

[firebase.service_account]
  type = "service_account"
  project_id = "personalized-drink-recommender"
  private_key_id = "e13db3ba92143f6ce7a12dc467dd7f09ccd05104"
  private_key = """
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbjDODK2Si3IGF\ntzL0SkUVoCkgVZ2yXf7C+0ur7yoQOaePgfPAD8iHxhFIUjCTdmS23vh0U87EXzlD\nWuMa/g7CGTbJKL/kQlpmRnQkOCqbBNFKwAgAzPPqMpT4Jyy/HcUbLDqRw4q5YyGj\nCXZReilObaP10PB/qHguwJYsGIpSRVIzh47dDmxzhy35zY9lQ3Em59rQ7gY7I/pZ\n79EzZfPrOjIjU88Y5rbtWKkEUPInHgKkoeyalwYcZHaEJ3RwrOTXEk/k77lH2ZGj\nFAz4faSFyrZlIirsHTTFXWxJLh5JZ3vd+orFr4/f5nnqJymMQrNK/Nkc0VZDIzKg\nP7UCn9d7AgMBAAECggEAK1AR8/98SWFPa7WEqcOYkxoC+a79d3J3A0JIYvr44oW7\nY9mSzzNV6oC7xUClqBo6lzVlR7cih0ngvyGqxZRi9adhuwfuzxeu5nXN11wQeRQR\nV1g7okVv0hH9q0/1RM58WUGqmXYyxcaV0jlLSgrTP7SGCGgC3/lAZfxYlLTMp3WY\nzC5OPhPN8zffChjMYePXUa1XkqMtrfB2OZ25chkkwDnOCnMQgSaPyZZZYgakxJU9\natQJrZuzfkhsaSTXIEwzVH4sff+evy2KVsXAOq6Kw3swV6p7X11DnGWTQNPW40IW\n9s1oDYdqnjI87b+MPBYPJStg8oYcK+WGWPCgVFhsKQKBgQDTGZ3maRRiqTEjXFuf\nSUQuJ6YV6U8bdKpsGyqlvuXqIfdzJXl0i6usXRu+Rn6a5si3KVeYlDr9gcWxrKXn\np/OQ2zQM6jUdtN5t1GwEHDiR6vGQNKiJM12nC0wTzvkCLtpHx2Z1eIhKcA25aFSp\np6dEyau9A9d0PjD6JbgAqfFvHQKBgQC8ocKR0fqSKGlXMfpBxY1rksSQdCiOmDU8\ndbu2wdtyp9LlUCBs0DbVbDKbTwp01WHgy+PKDHwHymMjtNMtEWY3ZhUZEyoX1qYb\nn9tvDK8pVIaU9THOlf3Wyk9MhQzIZXLB2703QB1Z7GegiYDFj993C4sEMedB/GSs\nSeUSec4ldwKBgQDHJlybWTidFya/SEs7i0AiFs+NzkwOB9MbJ8nlEaIPbrnmTE03\nkOiFNFWO/SxFcEGc4gi8beL08++QfeMKF50lZFbHdFBl1RMeJA8/FWyc5Du+Ip94\nyBerFnJQIasyzwaoPso/OlXBe9LGvlFYuEyKDYPSToR9KorEAr+DCNA3VQKBgBF0\nJjy34SeE9bpLtYxAa0V43xc+qEIJc2OUwTm31kZVoP323Ak1et1klYopVh5ZYCUc\nuIcJgLB32ZSENsYExiB6IZmgXFS4V8ZWlEdCNTLtz0YZKfKjjklBjvTVmskwGd42\nJtvl4tFfPndsQa4GEfdB6isJMwy3/dizPa7n9lshAoGAG3Ea0ROyDDR3HqELvzYh\nqfye53CRiyKFRrV9pxl74pG5Z7LDdkZJlKbS9qwY767JOvFbDCrwe+1lf5zZ+2GA\n0pyxIHhIDupTX0fNJytQS1rjMLBSEN0131FXZ7KtXbQw6WxqyDsohVumLMqrEQkQ\n49R8DIiC25YAkmbSU7mooFQ=
  -----END PRIVATE KEY-----
  """
  client_email = "firebase-adminsdk-fbsvc@personalized-drink-recommender.iam.gserviceaccount.com"
  client_id = "102141272003078143238"
  auth_uri = "https://accounts.google.com/o/oauth2/auth"
  token_uri = "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40personalized-drink-recommender.iam.gserviceaccount.com"
  universe_domain = "googleapis.com"
